# Generated by Django 3.0.4 on 2021-04-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
    ]
