# Generated by Django 3.0.4 on 2021-04-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='about_text',
            field=models.TextField(default='a'),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(default='a'),
        ),
    ]
